### ISSUE TITLE
[Bug]: No Elgato devices found

### ISSUE THREAD

**Issue by KoMa1978** [xXBJXx/ioBroker.elgato-key-light#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I installed an instance today but no devices are found. Great work and thanks a lot for all the effort building an adapter. Hopefully it will be integrated into the repository soon.

The devices (2x Keylight) are working, I already control them with iobroker through a JS script. So reason is more or less the MDNS discovery.

Running a tcpdump shows that the adapter is not sending a "discovery request" for devices but netstat show it is listening on port 5353.

In my case the Elgato devices are located in a different subnet and I use a homebridge, which itself is working fine (Elgato App on IOS and Windows are working fine).

Beside this mDNS issue I prefer to have a solution to manually add devices by IP/hostname.

Thanks a lot,
 KoMa1978

### Adapter version

0.0.3

**Comment by KoMa1978** [comment]
Short update ... 

If I run a TCPDUMP on the iobroker host and open the Elgato App on my iPhone (different VLAN as well), I can see mDNS traffic arriving on the iobroker:

192.168.xxx.xxx.5353 > 224.0.0.251.5353: [udp sum ok] 0*- [0q] 6/0/0 _elg._tcp.local. PTR Key Light 1._elg._tcp.local., key-light-1.local. (Cache flush) NSEC, Key Light 1._elg._tcp.local. (Cache flush) NSEC, key-light-1.local. (Cache flush) A 192.168.yyy.yyy, Key Light 1._elg._tcp.local. (Cache flush) TXT "mf=Elgato" "dt=200" "id=aa:aa:aa:aa:aa:aa" "md=Elgato Key Light Air bbbbbbbbbb" "pv=1.0", Key Light 1._elg._tcp.local. (Cache flush) SRV key-light-1.local.:9123 0 0 (243)

But they are still not shown in the WebUI.

**Comment by xXBJXx** [comment]
the mDNS does not work so well on some systems for me on the dev system Windows it works even with different VLAN on Linux but not I will disable the mDNS and then make a new menu to add devices

**Comment by xXBJXx** [comment]
@KoMa1978 
please install from GitHub and give it a try.
I deleted the mDNS search and add devices manually, also added a delete function in the UI.
![image](https://user-images.githubusercontent.com/32600934/215230516-409acb29-8a68-48d7-9044-f658bd364418.png)
when entering the IP, a . is automatically added after every 3rd digit

**Comment by KoMa1978** [comment]
Looks very good! Both Keylights are working and I have many datapoints ;-)

I'll now convert my JS to blockly and test the adapter. Thanks a lot!!
