### ISSUE TITLE
[Feature]: Rename Datapoints

### ISSUE THREAD

**Issue by KoMa1978** [xXBJXx/ioBroker.elgato-key-light#2]
### Is your feature request related to a problem? Please describe.

Please rename the datapoints from "datapoint" to "<<keylight / Info / Displayname>> - datapoint" example
Now: "Brightness"
Wanted: "Keylight Links - Brightness"

It is hard to understand a script if there are multiple keylights I want to control.

![image](https://user-images.githubusercontent.com/57285166/215435645-dbc82aab-a4d0-4d0b-a7aa-435e128aa97d.png)

**Comment by xXBJXx** [comment]
is it enough if i do this only for the `light.lights`? or should this be done for all states

**Comment by KoMa1978** [comment]
Hmm,

I would prefer to have all data points named similar.
If I look at my other objects, like HomeMatic, all the datapoints start with the "DeviceName" then a "." and the the datapoint:
![image](https://user-images.githubusercontent.com/57285166/216932157-654d5a1e-4958-4fd2-8329-772d443151a5.png)
I think this is the most flexible way.

**Comment by xXBJXx** [comment]
Please install from GitHub and try if it fits like this

**Comment by KoMa1978** [comment]
Looks very good! Thanks a lot!

There are some datapoints (maybe old ones) without the name and the folders have no name included ... OK not really needed but will look better ;-)

Just a personal opinion: I think a "." or "_" as separator between the devicename and datapoint would be better.

![image](https://user-images.githubusercontent.com/57285166/217083704-bc46c7ca-7e11-442a-ab36-b4b6e5ee34e5.png)

Again thanks a lot!! You should add this adapter to the default iobroker repository.

**Comment by xXBJXx** [comment]
The folder names I can also still adapt, and "." or "_" I can also still make.
The adapter will also be added to the ioBroker repo, but it has to run and be tested for a few weeks. 

I will make the request in a few days after that, it will take a few weeks until the adapter is tested, and possible bugs are fixed.

**Comment by xXBJXx** [comment]
The state name does not exist any more, you can delete it

**Comment by KoMa1978** [comment]
Great work!! Again!! Works much better than my Javasrcipts ;-)
I used a couple of days to turn on/of my video lights with a HomeMatic Switch and it very reliable.

**Comment by xXBJXx** [comment]
so that with the "." and "_" looks a little dof from there make states yes also names from märeren words have e.g. 
`elgato-key-light.0.EW40K1A09882.info.firmwareBuildNumber`
this will look like `Elgato Light Strip Test_Firmware Build Number` `Elgato Light Strip Test.Firmware Build Number`.
I could possibly put a "/" in there, that looks a bit better => `Elgato Light Strip Test / Firmware Build Number`.

**Comment by KoMa1978** [comment]
Yes you are right, a „/„ looks better. 

at least everything different from a whitespace makes it much clearer that it is a separator

**Comment by xXBJXx** [comment]
Have adjusted it, please check

**Comment by KoMa1978** [comment]
Niiiiiiiicccee ;-)

What I've seen is that the datapoint names are first letter uppercase for data points but not for folders.

And regarding the folders, does it make sense to name them "Name / Folder / Datapoint" (example: "Key Light RECHTS / Wifi-Info / SSID"? 

![image](https://user-images.githubusercontent.com/57285166/217188877-30910001-0d1f-4707-b1df-07f7b30ab17c.png)

Yes at the moment there are only unique names but I don't know if the other Elgato devices have subfolders with identical datapoint names, like lights.0 and lights.1:

![image](https://user-images.githubusercontent.com/57285166/217189303-79b99819-f498-4b01-ad69-688d79c3a25e.png)

Not needed by me, but maybe simply use the provided folder structure like "Key Light RECHTS / Light / Lights / 0 / Brighness" is more futureproof?

Thanks again for the great adapter!

**Comment by xXBJXx** [comment]
> Not needed by me, but maybe simply use the provided folder structure like "Key Light RECHTS / Light / Lights / 0 / Brighness" is more futureproof?

I won't do that with the path of the state in the name because that only drags out the name, and then you can't leave it under the objects anymore.

I close the topic, if there is something else you can open it again
