### ISSUE TITLE
[Feature]: Installation manual

### ISSUE THREAD

**Issue by Andariel78** [xXBJXx/ioBroker.elgato-key-light#3]
### Is your feature request related to a problem? Please describe.

see additional context

### Additional context

Hi, 

i would like an installation manual for IOBroker. 
Is there any chance to get one?

Thanks in advance
Andariel

**Comment by xXBJXx** [comment]
What do you mean by installation manual, the adapter will be installed like all other adapters from ioBroker as soon as it is added to the ioBroker repo. There is already a request open, only the ok from Apollon77 is still missing.

currently, you have to install it via the GitHub link or NPM
![image](https://user-images.githubusercontent.com/32600934/226744774-ec00edd3-7e64-4417-9583-ba478b908509.png)
![image](https://user-images.githubusercontent.com/32600934/226744934-a5ffdb56-e22d-423b-9792-befd6f90e135.png)

**Comment by Andariel78** [comment]
Japp, that´s exactly what I did, but:

![image](https://user-images.githubusercontent.com/49390915/227309306-8ff71182-a307-46bd-803f-82666da6db4b.png)

That´s why I thought there  is something missing, because there is no new instance.

**Comment by xXBJXx** [comment]
With a GitHub or NPM installation, no instance is created with it, one installs only the adapter code on the system one ioBroker instance must let them create itself.
To do this, simply search for Elgato Key Light in the adapters and in the tile, click on the three dots and then on the plus symbol, then an instance is created.
As soon as the adapter is in the ioBroker repo, an instance is automatically created during the installation.
![image](https://user-images.githubusercontent.com/32600934/227379479-a561dec3-10bf-4cd7-b813-b3dd63bcfe4c.png)

PS. 
There is even a note about this in the GitHub installation window
![image](https://user-images.githubusercontent.com/32600934/227380879-6fe8cda4-3a95-40ec-9fa9-1f10e133bf11.png)

**Comment by Andariel78** [comment]
Oh sorry, I totally forgot this.
Was the first installation since years.
Thank you very much.

Cheers
